# Generated by Django 2.1 on 2020-05-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoWeb',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('contenido', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contenido_web',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosBanco',
            fields=[
                ('numero_cuenta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('banco', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'datos_banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_habitacion', models.BigIntegerField(blank=True, null=True)),
                ('tipo_cama', models.CharField(max_length=20)),
                ('accesorios', models.CharField(max_length=20)),
                ('precio', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitacionesReserva',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'habitaciones_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'huesped',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HuespedesReserva',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'huespedes_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_menu', models.CharField(max_length=20)),
                ('documento_menu', models.BinaryField(blank=True, null=True)),
                ('precio', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monto_pago', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monto_total', models.BigIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('adjuntar_factura', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosPedidos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosSolicitados',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('fk_retiro_producto', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos_solicitados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('rubro', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('plantilla_huespedes', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetiroProducto',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'retiro_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosReserva',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'servicios_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
    ]
